### ISSUE TITLE
Error in calling client

### ISSUE THREAD

**Issue by prabal97** [coddingtonbear/python-myfitnesspal#72] opened 2018-09-25 17:41 UTC
import myfitnesspal as mfp
>>> client=mfp.Client('vaasitas')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/myfitnesspal/client.py", line 52, in __init__
    self._login()
  File "/usr/local/lib/python3.4/dist-packages/myfitnesspal/client.py", line 105, in _login
    self._auth_data = self._get_auth_data()
  File "/usr/local/lib/python3.4/dist-packages/myfitnesspal/client.py", line 126, in _get_auth_data
    return result.json()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by coddingtonbear** [comment] 2018-09-26 19:43
This looks like a duplicate of #71

**Closed by coddingtonbear** 2018-09-26 19:43 UTC

**Comment by coddingtonbear** [comment] 2018-09-26 19:45
Actually -- not a duplicate of #71 but of #68
